shop/dashboard/urls.py
from django.conf.urls import url
from shop.dashboard.views import HomeImagesList, HomeImagesCreateView
from shop.dashboard.views import ContactInfoUpdate

urlpatterns = [
    # Your other URLs
    url(r'^dashboard/contact_info/update/$', ContactInfoUpdate.as_view(
        template_name='dashboard/contact_info_update.html'),
        name='contact_info_update'),
    url(r'^dashboard/home_image/$', HomeImagesList.as_view(),
        name='home_images_list'),
    url(r'^dashboard/home_image/create/$', HomeImagesCreateView.as_view(
        template_name='dashboard/home_images_create.html'),
        name='home_images_create'),

]

shop/general_info/urls.py
from oscar.app import application
from django.conf.urls import url

from shop.general_info import views


urlpatterns = [
    # Your other URLs
    url(r'^callback/$', views.callback_view, name='callback'),
    # url(r'', include(application.urls)),
    ]

shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from django.conf.urls import include, url
from django.contrib import admin
from oscar.app import application


urlpatterns = [
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include(application.urls)),
    url(r'', include('shop.general_info.urls')),
    url(r'', include('shop.dashboard.urls')),
    url(r'^$', TemplateView.as_view(template_name='base.html')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/address/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from oscar.apps.address.abstract_models import AbstractUserAddress


class AbstractShippingMethod(models.Model):
    SHIPPING_METHOD_SELF = 'self'
    SHIPPING_METHOD_NEW_POST = 'new_post'
    SHIPPING_METHOD_CHOICES = (
        (SHIPPING_METHOD_SELF, _('Self pickup')),
        (SHIPPING_METHOD_NEW_POST, _('Pickup from new-post department'))
    )
    new_post_department = models.ForeignKey('new_post.Department', null=True, blank=True, verbose_name=_('New post department'))
    shipping_method = models.CharField(max_length=10, default=SHIPPING_METHOD_SELF, choices=SHIPPING_METHOD_CHOICES, verbose_name=_('Shipping method'))

    class Meta:
        abstract = True


class UserAddress(AbstractUserAddress, AbstractShippingMethod):
    pass

from oscar.apps.address.models import *  # noqa

shop/catalogue/models.py
from django.db import models
from oscar.apps.catalogue.abstract_models import AbstractProduct
import django_filters
from django.utils.translation import ugettext_lazy as _


class AbstractProductHomePage(models.Model):
    is_important = models.BooleanField(_('display on homepage'), default=False)

    class Meta:
        abstract = True


class Product(AbstractProduct, AbstractProductHomePage):
    pass


class ProductFilter(django_filters.FilterSet):
    name = django_filters.CharFilter(lookup_expr='iexact')

    price = django_filters.NumberFilter()
    price__gt = django_filters.NumberFilter(name='price', lookup_expr='gt')
    price__lt = django_filters.NumberFilter(name='price', lookup_expr='lt')

    # class Meta:
    #     model = Product
    #     fields = ['price', 'release_date']

from oscar.apps.catalogue.models import *  # noqa

shop/checkout/models.py
from oscar.apps.checkout.models import *  # noqa

shop/dashboard/catalogue/models.py
from oscar.apps.dashboard.catalogue.models import *  # noqa

shop/general_info/models.py
from django.db import models
from django.db.models.aggregates import Max
from phonenumber_field.modelfields import PhoneNumberField


class ContactInfo(models.Model):
    phone_first = models.CharField(max_length=100, null=True, blank=True)
    phone_second = models.CharField(max_length=100, null=True, blank=True)
    address = models.CharField(max_length=100, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    other = models.CharField(max_length=100, null=True, blank=True)


class HomeImages(models.Model):
    order = models.PositiveIntegerField(null=True)
    image = models.ImageField(upload_to='homepage_slider/')

    class Meta:
        ordering = ['order']

    def save(self, *args, **kwargs):
        # import pdb; pdb.set_trace()
        max_order = HomeImages.objects.all().aggregate(Max('order'))['order__max']
        self.order = max_order + 1
        super(HomeImages, self).save(*args, **kwargs)


class Callback(models.Model):
    phone = PhoneNumberField()
    name = models.CharField(max_length=20, null=True, blank=True)
    notes = models.CharField(max_length=100, null=True, blank=True)

shop/promotions/models.py
from oscar.apps.promotions.models import *  # noqa

shop/address/forms.py
from oscar.apps.address.forms import AbstractAddressForm
from oscar.apps.address import forms as oscar_forms
from shop.address.models import UserAddress
from shop.checkout.forms import ShippingAddressForm


class UserAddressForm(ShippingAddressForm):

    def __init__(self, user, *args, **kwargs):
        super(UserAddressForm, self).__init__(*args, **kwargs)
        self.instance.user = user

shop/catalogue/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _


class SortingForm(forms.Form):
    STARTS_WITH_CHEAP = "price"
    STARTS_WITH_EXPENSIVE = "-price"
    EMPTY_CHOICE = ''
    ORDER_CHOICES = (
        (EMPTY_CHOICE, _('No order')),
        (STARTS_WITH_CHEAP, _('From cheap to expensive')),
        (STARTS_WITH_EXPENSIVE, _('From expensive to cheap'))
    )
    order = forms.ChoiceField(choices=ORDER_CHOICES, label="", help_text="",)

shop/checkout/forms.py
from django.core.urlresolvers import reverse_lazy
from oscar.apps.address.forms import AbstractAddressForm
from oscar.apps.checkout import forms as oscar_forms
from django.utils.translation import ugettext_lazy as _

from shop.new_post.models import City
from shop.order.models import ShippingAddress
from dal import autocomplete
from django import forms


class ShippingAddressForm(AbstractAddressForm):
    new_post_city = forms.ModelChoiceField(
        label=_('City'),
        required=False,
        queryset=City.objects.all(),
        widget=autocomplete.ModelSelect2(url=reverse_lazy('checkout:city-autocomplete'))
    )

    def __init__(self, *args, **kwargs):
        super(ShippingAddressForm, self).__init__(*args, **kwargs)
        self.fields['phone_number'].required = True

    def clean(self):
        cleaned_data = super(ShippingAddressForm, self).clean()
        shipping_method = cleaned_data.get('shipping_method')
        new_post_department = cleaned_data.get("new_post_department")

        if shipping_method == ShippingAddress.SHIPPING_METHOD_NEW_POST:
            if not new_post_department:
                self.add_error('new_post_department', 'This field is required.')
        return cleaned_data

    def adjust_country_field(self):
        pass

    class Meta(oscar_forms.ShippingAddressForm.Meta):
        model = ShippingAddress
        fields = [
            'first_name', 'last_name', 'phone_number', 'shipping_method', 'new_post_city',
            'new_post_department', 'notes',
        ]
        widgets = {
            'new_post_department': autocomplete.ModelSelect2(url=reverse_lazy('checkout:department-autocomplete'), forward=['new_post_city'])
        }


from django import forms

shop/dashboard/catalogue/forms.py
import oscar.apps.dashboard.catalogue.forms as oscar_forms


class ProductForm(oscar_forms.ProductForm):
    class Meta(oscar_forms.ProductForm.Meta):
        fields = ['title', 'upc', 'description', 'is_important',
                  'is_discountable', 'structure']


class StockRecordForm(oscar_forms.StockRecordForm):
    class Meta(oscar_forms.StockRecordForm.Meta):
        fields = [
            'partner', 'partner_sku','price_currency',
            'price_excl_tax','num_in_stock', 'low_stock_threshold',
        ]

shop/general_info/forms.py
from django import forms
from django.forms.models import ModelForm

from shop.general_info.models import Callback


class CallbackForm(ModelForm):
    class Meta:
        model = Callback
        fields = ['name', 'phone']

    def __init__(self, *args, **kwargs):
        super(CallbackForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs['class'] = 'form-control'

shop/catalogue/views.py
from oscar.apps.catalogue import views as oscar_views
from shop.catalogue.forms import SortingForm


class ProductCategoryView(oscar_views.ProductCategoryView):

    def get_page_list(self, paginator):
        curr_page_num = self.request.GET.get('page', '')
        if not curr_page_num.isdigit():
            curr_page_num = 1
        curr_page_num = int(curr_page_num)
        last_page_num = paginator.num_pages
        curr_page = paginator.page(curr_page_num)
        prev_page_num = None
        next_page_num = None
        if curr_page.has_previous():
            prev_page_num = curr_page.previous_page_number()
        if curr_page.has_next():
            next_page_num = curr_page.next_page_number()
        param = self.request.GET.copy()
        if 'page' in param:
            param.pop('page')
        res = []

        if curr_page_num > 1:
            res.append({'url': '?page={}{}'.format(prev_page_num, '&'+param.urlencode()), 'title': 'Prev', 'active': True, 'direction': 'previous'})
            if curr_page_num > 3:
                res.append({'url': '?page=1', 'title': '1', 'active': True},)
                res.append({'url': None, 'title': None, 'active': True,'direction': 'active'})
            if curr_page_num == 3:
                res.append({'url': '?page=1', 'title': '1', 'active': True})
            res.append({'url': '?page={}{}'.format(prev_page_num, '&'+param.urlencode()), 'title': prev_page_num, 'active': True, 'direction': 'previous'})
        else:
            res.append({'url': None, 'title': 'Prev', 'active': False, 'direction': 'previous active'})

        res.append({'url': None, 'title': curr_page_num, 'active': False, 'direction': 'active'},)

        if curr_page_num < last_page_num:
            res.append({'url': '?page={}{}'.format(next_page_num, '&'+param.urlencode()), 'title': next_page_num, 'active': True, 'direction': 'next'})
            if last_page_num - curr_page_num > 2:
                res.append({'url': None, 'title': None, 'active': True,'direction': 'active'})
                res.append({'url': '?page={}{}'.format(last_page_num, '&'+param.urlencode()), 'title': last_page_num, 'active': True})
            if last_page_num - curr_page_num == 2:
                res.append({'url': '?page={}{}'.format(last_page_num, '&'+param.urlencode()), 'title': last_page_num, 'active': True})
            res.append({'url': '?page={}{}'.format(next_page_num, '&'+param.urlencode()), 'title': 'Next', 'active': True,'direction': 'next'})
        else:
            res.append({'url': None, 'title': 'Next', 'active': False,'direction': 'next active',})
        return res

    def get_context_data(self, **kwargs):
        context = super(ProductCategoryView, self).get_context_data(**kwargs)
        context['category'] = self.category
        search_context = self.search_handler.get_search_context_data(
            self.context_object_name)
        context.update(search_context)
        context['sorting_form'] = SortingForm(initial={'order': self.request.GET.get('order')})
        context['page_list'] = self.get_page_list(context['paginator'])
        return context



case_curr_page_is_5 = [
    {'url': '.../?page=4', 'title': 'prev', 'active': True},
    {'url': '.../?page=1', 'title': '1', 'active': True},
    {'url': '.../?page=3', 'title': '...', 'active': True},
    {'url': '.../?page=4', 'title': '4', 'active': True},
    {'url': None, 'title': '5', 'active': False},
    {'url': '.../?page=6', 'title': '6', 'active': True},
    {'url': '.../?page=7', 'title': '...', 'active': True},
    {'url': '.../?page=10', 'title': '10', 'active': True},
    {'url': '.../?page=6', 'title': 'next', 'active': True},
]

case_curr_page_is_1 = [
    {'url': None, 'title': 'prev', 'active': False},
    {'url': None, 'title': '1', 'active': False},
    {'url': '.../?page=2', 'title': '2', 'active': True},
    {'url': '.../?page=3', 'title': '...', 'active': True},
    {'url': '.../?page=2', 'title': 'next', 'active': True},
]

shop/checkout/views.py
from oscar.apps.checkout import views as oscar_views
from django.shortcuts import redirect
from dal import autocomplete

from shop.new_post.models import City, Department


class ShippingMethodView(oscar_views.ShippingMethodView):
    def get_success_response(self):
        return redirect('checkout:preview')


class ShippingAddressView(oscar_views.ShippingAddressView):

    def get_available_addresses(self):
        # Include only addresses where the country is flagged as valid for
        # shipping. Also, use ordering to ensure the default address comes
        # first.
        return self.request.user.addresses.all().order_by('-is_default_for_shipping')


class CityAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):

        qs = City.objects.all()

        if self.q:
            qs = qs.filter(name__icontains=self.q)

        return qs


class DepartmentAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):

        qs = Department.objects.all()

        new_post_city = self.forwarded.get('new_post_city', None)
        if new_post_city:
            qs = qs.filter(city=new_post_city)

        if self.q:
            qs = qs.filter(description__icontains=self.q)

        return qs

shop/dashboard/views.py
from django.http.response import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404
from django.views.generic.edit import UpdateView
from shop.dashboard.tables import HomeImagesTable
from shop.general_info.models import ContactInfo
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormMixin
from django_tables2.views import SingleTableMixin
from django.views.generic.edit import CreateView
from django.core.urlresolvers import reverse_lazy
from shop.general_info.models import HomeImages


class HomeImagesList(SingleTableMixin, FormMixin, TemplateView):
    template_name = 'dashboard/home_images_list.html'
    table_pagination = True
    model = HomeImages
    table_class = HomeImagesTable
    context_table_name = 'images'

    def get_queryset(self):
        qs = self.model.objects.all()
        return qs

    def post(self, request, *args, **kwargs):
        if 'delete_id' in request.POST:
            obj = get_object_or_404(HomeImages, id=request.POST['delete_id'])
            obj.delete()
            return HttpResponseRedirect('.')
        if request.POST.get('action') == 'order':
            list_id = request.POST.getlist('ids')
            obj_list = HomeImages.objects.filter(id__in=map(int, list_id))
            order = 1
            for obj in obj_list:
                obj.order = order
                obj.save()
                order += 1
            return JsonResponse({'success': True})


class HomeImagesCreateView(CreateView):
    model = HomeImages
    fields = ['image']
    success_url = reverse_lazy('home_images_list')


class ContactInfoUpdate(UpdateView):
    model = ContactInfo
    fields = '__all__'
    success_url = reverse_lazy('dashboard:index')

    def get_object(self):
        return ContactInfo.objects.get()

shop/general_info/views.py
from django.http.response import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.core.mail import send_mail
from oscar.apps.customer.models import CommunicationEventType
from oscar.apps.dashboard.nav import default_access_fn

from shop.general_info.models import ContactInfo

from shop.general_info.forms import CallbackForm
from django.core import mail
from django.conf import settings
from django.views.generic.edit import UpdateView


def callback_view(request):
    form = CallbackForm()
    if request.method == 'GET':
        return render(request, 'elements/callback_form.html', {'callback_form': form})
    if request.method == 'POST':
        form = CallbackForm(request.POST)
        if form.is_valid():
            form.save()
            to_email = ContactInfo.objects.first().email
            phone = form.cleaned_data.get('phone')
            name = form.cleaned_data.get('name')
            with mail.get_connection() as connection:
                mail.EmailMessage('New callback was ordered',
                                  'User {} with phone {} ordered a callback on site {}'.format(name, phone, settings.OSCAR_SHOP_NAME),
                                  settings.OSCAR_FROM_EMAIL,
                                  to=[to_email],
                                  connection=connection).send()

            return JsonResponse({'success': True, 'errors': None}, status=201)
        else:

            return JsonResponse({'success': False, 'errors': form.errors}, status=400)

shop/promotions/views.py
from oscar.apps.promotions import views as oscar_views
from shop.catalogue.models import Product
from shop.general_info.models import HomeImages


class HomeView(oscar_views.HomeView):
    template_name = 'promotions/home.html'
    context_object_name = 'product_list'

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['product_list'] = Product.objects.filter(is_important=True)
        context['img_slider'] = HomeImages.objects.all()
        return context

shop/templates/catalogue/catalogue_intro.html
{% load i18n %}
{% load static %}
{% load category_tags %}
{% load thumbnail %}
{% load display_tags %}


<div class="collections">
	<div class="collections-head">
		<div class="container">
			<div class="collections-head-left">
				{% thumbnail category.image "494x285" crop="center" as im %}
				<img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" title="name" />
				{% endthumbnail %}
			</div>
			<div class="collections-head-right">
				<h2><span>{{category.name}}</span></h2>
			</div>
			<div class="clearfix"> </div>
		</div>
	</div>
	<!-- categories -->


		<div class="categories">
		<div class="container">
			<div class="categories-left">

				<ul>
					<li>
						<a href="{{ homepage_url }}">{% trans "Home" %}<span class="glyphicon glyphicon-chevron-right"></span></a>
					</li>

					{% for item in category.get_ancestors %}
					<li>
						<a href="{{ item.get_absolute_url }}">{{ item.name }}<span class="glyphicon glyphicon-chevron-right"></span></a>
					</li>
					{% endfor %}
					{%if detail%}
					<li>
						<a href="{{ category.get_absolute_url }}">{{ category.name }}<span class="glyphicon glyphicon-chevron-right"></span></a>
					</li>

					<li>
						<span class="last_item">{{ product.get_title }}</span>
					</li>
					{%else%}
					<li>
						<span class="last_item">{{ category.name }}</span>
				    </li>
					{%endif%}
				</ul>
			</div>
			    {%if not detail%}
				<div class="categories-right" style="color: #fff">
					<ul>
					{% if paginator.num_pages > 1 %}
						{%for item in page_list%}
						<li {%if item.direction%} class="{{item.direction}}"{%endif%}>
							{%if not item.title %}
								<span>...</span>
							{%elif not item.active%}
								<a><span>{{item.title}}</span></a>
							{%else%}
								<a href="{{item.url}}">{{item.title}}</a>
							{%endif%}
						</li>

					    {% endfor %}
					{% endif %}
					<!--{% blocktrans with page_num=page_obj.number total_pages=paginator.num_pages %}-->
					<!--<li>Page {{ page_num }} of {{ total_pages }}</li>-->
					<!--{% endblocktrans %}-->
					<!--<li class="view"><a href="/catalogue/">View All</a></li>-->
						<li class="options">
							<form method="GET" id="order_form" action="{{ category.get_absolute_url }}" >
								{{sorting_form}}
							</form>
						</li>
					<div class="clearfix"> </div>
					</ul>
				</div>
			{%endif%}
			<div class="clearfix"> </div>
		</div>
	</div>
</div>

shop/templates/catalogue/category.html
{% extends "layout.html" %}
{% load reviews_tags %}
{% load thumbnail %}
{% load basket_tags %}
{% load promotion_tags %}
{% load category_tags %}
{% load product_tags %}
{% load i18n %}
{% load static %}
{% load purchase_info_tags %}
{% load currency_filters %}
{% load reviews_tags %}
{% load display_tags %}

{% block title %}
    {{ shop_name }} |
    {% for item in category.get_ancestors %}
        {{ item.name }} |
    {% endfor %}
    {{category.name}}
{% endblock title %}

{% block content_wrapper  %}
    {%block category_intro%}
        {% include "catalogue/catalogue_intro.html" %}
    {%endblock category_intro%}
    {%block messages%}
	<div class="container ">
        {% include "partials/alert_messages.html" %}
		</div>
    {%endblock messages%}
	<div class="iteam-grids">
	<div class="container no-padding">
		{% for product in products %}
			{% include "catalogue/category_and_search_content.html" %}
		{%endfor%}
	</div>
	</div>
{% endblock %}

{% block onbodyload %}{{ block.super }}
$('#id_order').on('change', function(){
	$( "#order_form" ).submit();

});
{% endblock %}

shop/templates/catalogue/category_and_search_content.html
{% load thumbnail %}
{% load i18n %}



<div class="col-md-3">
    <div onclick="{{ product.get_absolute_url }}" class="iteam-grid text-center">

        {% with image=product.primary_image %}
        {% thumbnail image.original "150x150" crop="center" as im %}
        <a href="{{ product.get_absolute_url }}"><img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" title="name" /></a>
        {% endthumbnail %}
        {% endwith %}
        <span>{{ product.get_title|truncatewords:4 }}</span>
        <label>{% include "elements/stock_record.html" %}</label>
        <div class="button-group">
            <ul>

                <li>
                    {% if not product.is_parent %}
                        {% include "basket/add_to_basket_form_compact.html" %}
                    {% endif %}
                </li>


                <li>
                    <a class="more" href="{{ product.get_absolute_url }}">{% trans 'More' %}</a>
                </li>

                <div class="clearfix"> </div>
            </ul>
        </div>
    </div>
</div>

shop/templates/catalogue/detail.html
{% extends "layout.html" %}
{% load reviews_tags %}
{% load thumbnail %}
{% load basket_tags %}
{% load promotion_tags %}
{% load category_tags %}
{% load product_tags %}
{% load i18n %}
{% load static %}
{% load purchase_info_tags %}
{% load currency_filters %}
{% load reviews_tags %}
{% load display_tags %}




{% block styles %}
    {{block.super}}
    <link href="{% static 'css/owl.carousel.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/etalage.css' %}">
{% endblock %}

{% block title %}
    {{ shop_name }} |
    {% for item in product.get_categories.first.get_ancestors %}
        {{ item.name }} |
    {% endfor %}

    {{product.get_categories.first}} | {{ product.get_title }}
{% endblock title %}

{% block content_wrapper %}

{% include "catalogue/catalogue_intro.html" with detail=True category=product.get_categories.first%}
{%block messages%}
    <div class="container">
	{% include "partials/alert_messages.html" %}
	</div>
{%endblock messages%}
<div class="product-single-details">
    <div class="container">


    {% if product.images.all%}

	{% include "catalogue/etalage_detail_img.html" %}

    {%else%}
        <ul id="etalage" class="etalage" style="display: block; width: 314px; height: 552px;">
        <li class="" style="display: list-item; opacity: 1; background-image: none;">
            <img class="etalage_thumb_image" src="{% static 'images/photo_na.jpg'%}" style="display: inline; opacity: 1;width:300px;height:400px">
        </li>
        </ul>
    {%endif%}
		<div class="product-single-details-right">
			<div class="row">
				<h2>{{ product.get_title }}
					{%if product.upc%}
						<small class="pull-right">Product Code:{{ product.upc }}</small>
					{%endif%}
				</h2>
			</div>
			<!-- price-details -->
			<div class="price-details">
				<div class="price-details-left">
					<p>Price: {% include "elements/stock_record.html" %}</p>
				</div>
				<div class="price-details-right">
					{% include "basket/add_to_basket_form_compact.html" with detail=True%}
				</div>
				<div class="clearfix"> </div>
			</div>
			{% if product.description %}
			<div class="product-description">
				<h3>Description:</h3>
				<div class="des-tabs">
					<div class="tab1 tab">
						{{ product.description }}
					</div>
				</div>
			</div>
			{% endif %}
		</div>
    </div>
</div>
<div class="clearfix"> </div>

{% endblock content_wrapper %}

{% block extrascripts %}
    {{ block.super }}
    <script src="{% static 'js/jquery.etalage.min.js' %}"></script>
    <script>
	jQuery(document).ready(function($){

		$('#etalage').etalage({
			thumb_image_width: 300,
			thumb_image_height: 400,
			source_image_width: 900,
			source_image_height: 1000,
			show_hint: true,
			click_callback: function(image_anchor, instance_id){
				alert('Callback example:\nYou clicked on an image with the anchor: "'+image_anchor+'"\n(in Etalage instance: "'+instance_id+'")');
			}
		});
		// This is for the dropdown list example:
		//$('.dropdownlist').change(function(){
		//    etalage_show( $(this).find('option:selected').attr('class') );
		//});
	});
    </script>
    <script>
        $(document).ready(function(){
            $(".tab2 p").hide();
            $(".tab3 p").hide();
            $(".tab2 h4").click(function(){
                $(".tab2 p").slideToggle(300);
                $(".tab1 p").hide();
                $(".tab3 p").hide();
            });
            $(".tab1 h4").click(function(){
                $(".tab1 p").slideToggle(300);
                $(".tab2 p").hide();
                $(".tab3 p").hide();
            });
            $(".tab3 h4").click(function(){
                $(".tab3 p").slideToggle(300);
                $(".tab2 p").hide();
                $(".tab1 p").hide();
            });
        });
    </script>
{% endblock %}

shop/templates/catalogue/etalage_detail_img.html
{% load thumbnail %}
<div class="product-single-details-left">
	<div class="details-left">
		<div class="details-left-slider">
			<ul id="etalage" class="etalage" style="display: block; width: 314px; height: 552px;">

				{% for image in product.images.all%}

				<li class="" style="display: list-item; opacity: 1; background-image: none;">
					{% thumbnail image.original "300x400" crop="center" as im %}
					<img class="etalage_source_image" src="{{im.url}}">
					<img class="etalage_thumb_image" src="{{im.url}}"  width="{{ im.width }}" height="{{ im.height }}" style="display: inline; opacity: 1;">
					{% endthumbnail %}
				</li>
				{%endfor%}
			</ul>
		</div>
	</div>
</div>